apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hello-virtualservice
spec:
  gateways:
    - hello-gateway
  hosts:
    - '*'
  http:
    - match:
        - headers:
            X-PLT-User-Id:
              exact: 'testUser'
      route:
        - destination:
            host: hello-service.default.svc.cluster.local
            port:
              number: 8080
            subset: 'canaryversiontestUser'
    - route:
        - destination:
            host: hello-service.default.svc.cluster.local
            port:
              number: 8080
            subset: deployversion
